flex verify pt 2
git-svn-id: http://abstrakraft.org/cwiid/svn/cwiid/trunk@10 918edb2d-ff29-0410-9de2-eb38e7f22bc7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2888,6 +2888,11 @@ if test "$LEX" != "flex"; then
 echo "$as_me: error: flex not found" >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "`echo %%|$LEX -t --noyywrap|grep yypop_buffer_state`"; then
+	{ { echo "$as_me:$LINENO: error: flex missing yypop_buffer_state - upgrade to version 2.5.33 or later" >&5
+echo "$as_me: error: flex missing yypop_buffer_state - upgrade to version 2.5.33 or later" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 for ac_prog in 'bison -y' byacc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
